// <auto-generated />
using Cmsify.Sqlite.MigrationProbe.Fixtures;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cmsify.Sqlite.MigrationProbe.Fixtures
{
    [DbContext(typeof(UpgradeContext))]
    [Migration("20261004022859_FixtureRequiredName")]
    partial class FixtureRequiredName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Cmsify.Sqlite.MigrationProbe.Fixtures.FixtureChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("fixture_children", (string)null);
                });

            modelBuilder.Entity("Cmsify.Sqlite.MigrationProbe.Fixtures.FixtureParent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("fixture_parents", (string)null);
                });

            modelBuilder.Entity("Cmsify.Sqlite.MigrationProbe.Fixtures.FixtureChild", b =>
                {
                    b.HasOne("Cmsify.Sqlite.MigrationProbe.Fixtures.FixtureParent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
