<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RazorLangVersion>Latest</RazorLangVersion>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cmsify.Contracts\Cmsify.Contracts.csproj" />
    <ProjectReference Include="..\Cmsify.Core\Cmsify.Core.csproj" />
    <ProjectReference Include="..\..\sdk\dotnet\src\SyntaxCircus.Cmsify.Client\SyntaxCircus.Cmsify.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.SassCompiler" />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SyntaxCircus.AspNetCore.Common" />
    <PackageReference Include="SyntaxCircus.AspNetCore.Serilog" />
    <PackageReference Include="SyntaxCircus.Blazor.Auth" />
    <PackageReference Include="SyntaxCircus.Blazor.Components" />
    <PackageReference Include="SyntaxCircus.DotEnv" />
    <PackageReference Include="SyntaxCircus.Observability" />
  </ItemGroup>
</Project>
